import { Case } from './types'

export const cases: Case[] = [
  {
    project: 'Dragons Arena',
    link: 'https://discord.gg/h6T9vp3J86',
    encryptedWord: 'Jade38',
    encryptedWalletWord: 'tournament',
    availableDate: new Date('2022-09-27T15:00:00'),
  },
  {
    project: 'PLATA',
    link: 'https://twitter.com/plataNetwork',
    imgUrl: '/project_logos/plata.jpg',
    encryptedWord: 'topaz87',
    encryptedWalletWord: 'poker',
    availableDate: new Date('2022-09-28T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    imgUrl: '/project_logos/elrond_mafia.webp',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
  {
    project: 'Elrond Mafia',
    link: 'https://discord.gg/jZZRrD8Qbz',
    encryptedWord: 'emerald29',
    encryptedWalletWord: 'flop',
    availableDate: new Date('2022-09-29T15:00:00'),
  },
]
