import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&family=WindSong:wght@500&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <div className={styles.step1}>
          <h1 className={styles.title}>
            Elrond <br/>Treasure <br/> Hunt
          </h1>
        </div>
      </main>

      <main className={styles.main2}>
        <h1 className={styles.bookTitle}>
          Elrond Treasure Hunt
        </h1>
        <div className={styles.bookDesc}>
          <p>Welcome travellers !</p>
          <p>Rules :</p>
        </div>
      </main>

      <main className={styles.main3}>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/HODLcards"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/twitter-logo.webp" alt="Twitter Logo" width={25} height={25} />
          </span>
        </a>
        <div className={styles.madeWith}>Made with ❤️ for
          <a href="https://elrond.com/"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.elrondLogo}><Image src="/elrond-logo.svg" alt="Elrond Logo" width={20} height={20} /></a>Community</div>
      </footer>
    </div>
  )
}

export default Home
