import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <section className={styles.treasureMapSection}>
          <Image
            className={styles.bgImage}
            src="/page1.png"
            alt="treasure map"
            layout="fill"
            objectFit="cover"
            objectPosition="center"
            priority
          />
          <h1 className={styles.title}>
            Elrond <br />
            Treasure <br />
            Hunt
          </h1>
        </section>

        <section className={styles.rulesSection}>
          <Image
            className={styles.bgImage}
            src="/page2.png"
            alt="book of rules"
            layout="fill"
            objectFit="cover"
            objectPosition="center"
          />
          <div className={styles.book}>
            <h1 className={styles.bookTitle}>Elrond Treasure Hunt</h1>
            <div className={styles.bookDesc}>
              <p>Welcome travellers !</p>
              <p>Rules :</p>
            </div>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/HODLcards"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image
              src="/twitter-logo.webp"
              alt="Twitter Logo"
              width={25}
              height={25}
            />
          </span>
        </a>
        <div className={styles.madeWith}>
          Made with ❤️ for
          <a
            href="https://elrond.com/"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.elrondLogo}
          >
            <Image
              src="/elrond-logo.svg"
              alt="Elrond Logo"
              width={20}
              height={20}
            />
          </a>
          Community
        </div>
      </footer>
    </div>
  )
}

export default Home
